import { assess } from '@/core/guard/assess';
import { buildDay } from '@/core/planner/buildDay';
import { addDays, planClock, toPlanMinute, weekdayOf } from '@/core/time';
import type { Adjustment, DayPlan, DayTemplate, Flag, GuardState } from '@/core/types';
import type { RepositoryClient } from '@/lib/db/repository';
import { repositories } from '@/lib/db/repositories';
import { getDaySummaries } from '@/lib/db/daySummary';
import { settingsToDomain } from '@/lib/db/settingsMapping';
import { rowToBlock } from './reflowDay';

export interface FuturePlanPreview {
  plan: DayPlan;
  /** 'existing' when a real plans row is already there (e.g. tomorrow,
   *  generated by tonight's evening check-in, or an earlier Plan-ahead
   *  save); 'generated' when this call built it on the spot from the
   *  weekday template — the one honest difference the UI must show CT
   *  before they edit it. */
  source: 'existing' | 'generated';
  state: GuardState;
  flags: Flag[];
  adjustments: Adjustment[];
}

/** Spec B: a future date has no plan row until either the real overnight
 * generation reaches it or CT saves one through this page first. Loads the
 * real plan when one exists; otherwise builds an on-the-spot preview from
 * the weekday template using the same guard/adjustment pipeline
 * `ensureTodayPlan` uses for real generation. Writes nothing either way —
 * same contract as `previewEdits` in reflowDay.ts.
 *
 * The guard assessment always runs against CT's most recent real history
 * (`now`, i.e. today) rather than history "as of" the future `date` — a
 * date more than a few days out mostly or entirely has no history of its
 * own yet. This is a best-effort preview, not a prophecy: the same
 * approximation `ensureTodayPlan` and `generateTomorrowPlan` already make
 * one day at a time, just extended a few days further out. */
export async function previewFuturePlan(client: RepositoryClient, date: string, now: Date): Promise<FuturePlanPreview> {
  const repos = repositories(client);
  const settingsRow = await repos.settings.get();
  if (!settingsRow) throw new Error('No settings row yet — onboarding must run first.');
  const settings = settingsToDomain(settingsRow);

  const existingPlan = await repos.plans.get(date, 'date');
  if (existingPlan) {
    const blockRows = await repos.blocks.list({ date } as never);
    const plan: DayPlan = {
      date,
      wake: toPlanMinute(settings.wakeTime),
      bedtime: toPlanMinute(settings.bedtime),
      blocks: blockRows.map(rowToBlock),
    };
    return {
      plan,
      source: 'existing',
      state: existingPlan.state,
      flags: existingPlan.flags as Flag[],
      adjustments: existingPlan.adjustments as Adjustment[],
    };
  }

  const templateRow = await repos.templates.get(weekdayOf(date));
  if (!templateRow) throw new Error(`No template for weekday ${weekdayOf(date)} — nothing to preview yet.`);
  const template: DayTemplate = { weekday: templateRow.weekday, restDay: templateRow.rest_day, blocks: templateRow.blocks };

  const { planDate: todayDate } = planClock(now, settings.timezone);
  const history = await getDaySummaries(client, addDays(todayDate, -7), addDays(todayDate, -1));
  const assessment = assess(history, settings);
  const { plan } = buildDay(template, date, settings, assessment.adjustments);

  return { plan, source: 'generated', state: assessment.state, flags: assessment.flags, adjustments: assessment.adjustments };
}
